// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSPQxn2Q08TqcIgV9o34OzL0Vqb57pQZw',
    appId: '1:78886161874:web:e4aa69cb4a70ff9ae08c0b',
    messagingSenderId: '78886161874',
    projectId: 'trackone-83568',
    authDomain: 'trackone-83568.firebaseapp.com',
    storageBucket: 'trackone-83568.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJASzsFMFPBYdFxXM37q_gOCNVwZdas5c',
    appId: '1:78886161874:android:393622b9a3ad491ce08c0b',
    messagingSenderId: '78886161874',
    projectId: 'trackone-83568',
    storageBucket: 'trackone-83568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEb7pCrIeHRZm0nsP-tkNKCmFoYQBD0eI',
    appId: '1:78886161874:ios:48d656d6d6e65f68e08c0b',
    messagingSenderId: '78886161874',
    projectId: 'trackone-83568',
    storageBucket: 'trackone-83568.appspot.com',
    iosClientId: '78886161874-3q6il7p9qqgsr393uhn6lqp4hb6vpt9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEb7pCrIeHRZm0nsP-tkNKCmFoYQBD0eI',
    appId: '1:78886161874:ios:48d656d6d6e65f68e08c0b',
    messagingSenderId: '78886161874',
    projectId: 'trackone-83568',
    storageBucket: 'trackone-83568.appspot.com',
    iosClientId: '78886161874-3q6il7p9qqgsr393uhn6lqp4hb6vpt9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackOne',
  );
}
